server:
  port: 8080

spring:
  main:
    lazy-initialization: false
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:oracle:thin:@192.168.0.100:1521/orcl
    username: my_user
    password: my_password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 3600000    # 1 hour
      max-lifetime: 3600000    # 1 hour
      connection-timeout: 10000  # 10 seconds
      validation-timeout: 3000   # 3 seconds
      pool-name: HikariCP-Pool
      validation-query: SELECT 1 FROM DUAL

  cloud:
    gateway:
      routes:
        preload: true
      httpclient:
        pool:
          max-idle-time: 3600000
          max-life-time: 3600000
          min-idle: 5
        connect-timeout: 60000
        response-timeout: 3600000
        tcp:
          keep-alive: true
          idle-timeout: 3600000
      default-filters:
        - RemoveResponseHeader=Server
        - RemoveResponseHeader=Age
        - RemoveResponseHeader=X-Nf-Request-Id
        - RemoveResponseHeader=Cache-Status
        - AddRequestHeader=Connection,keep-alive
        - AddRequestHeader=Accept,application/json, text/plain, */*
        - AddRequestHeader=Accept-Language,bg
        - AddRequestHeader=Cache-Control,no-cache
        - AddRequestHeader=Connection,keep-alive

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
