server:
  reactive:
    netty:
      max-chunk-size: 16KB
      max-header-size: 16KB
      max-initial-line-length: 8KB
      idle-timeout: 600000
      lifecycle:
        timeout-per-shutdown-phase: 300000
  port: 8443
  http2:
    enabled: true
  ssl:
    session-cache-size: 5000
    session-timeout: 600
    enabled: true
    key-store: classpath:cert/keystore.p12
    key-store-password: your-password
    ciphers:
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
        step: 30s

spring:
  webflux:
    thread-pool:
      max-threads: 100
      queue-capacity: 500
  main:
    lazy-initialization: false
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:oracle:thin:@${CMS_DB_HOST}:1521/${CMS_DB_SN}
    username: ${CMS_DB_USER}
    password: ${CMS_DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-query: SELECT 1 FROM DUAL
      initialization-fail-timeout: 0

  cloud:
    gateway:
      routes:
        preload: true
      httpclient:

        h2c: true
        ssl:
          use-insecure-trust-manager: true
        pool:
          max-idle-time: 300000
          max-life-time: 1800000
          min-idle: 10
        connect-timeout: 30000
        response-timeout: 300000
        tcp:
          keep-alive: true
          idle-timeout: 600000

reactor:
  netty:
    ioWorkerCount: 8
    resolver:
      cache:
        ttl: 3600s
        negative-ttl: 10s

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
